### ISSUE TITLE
Test failure in nightly MIPS test

### ISSUE THREAD

**Issue by mcroomp** [Lokathor/wide#137]
Seems like there's a problem with the nightly build of Rust on MIPS. The stable and older builds work ok, but the nightly builds fail with errors in the shift tests. Looks like this might be a compiler problem.

failures:
    t_i64x2::impl_shl_for_i64x2
    t_i64x4::impl_shl_for_i64x4
    t_i64x4::impl_shr_for_i64x4
    t_u64x2::impl_shl_for_u64x2
    t_u64x2::impl_shr_for_u64x2
    t_u64x4::impl_shl_for_u64x4
    t_u64x4::impl_shr_for_u64x4

---- t_i64x2::impl_shl_for_i64x2 stdout ----
thread 't_i64x2::impl_shl_for_i64x2' panicked at tests/all_tests/t_i64x2.rs:69:3:
assertion `left == right` failed
  left: (-8, -8)
 right: (-12884901896, -12884901896)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- t_i64x4::impl_shl_for_i64x4 stdout ----
thread 't_i64x4::impl_shl_for_i64x4' panicked at tests/all_tests/t_i64x4.rs:76:3:
assertion `left == right` failed
  left: (-8, -8, 262140, 0)
 right: (-12884901896, -12884901896, 262140, 0)

---- t_i64x4::impl_shr_for_i64x4 stdout ----
thread 't_i64x4::impl_shr_for_i64x4' panicked at tests/all_tests/t_i64x4.rs:86:3:
assertion `left == right` failed
  left: (2305843009213693951, 2305843009213693951, 16383, 0)
 right: (2305843005992468[479](https://github.com/Lokathor/wide/actions/runs/6215172943/job/16867793003#step:6:480), 2305843005992468479, 16383, 0)

---- t_u64x2::impl_shl_for_u64x2 stdout ----
thread 't_u64x2::impl_shl_for_u64x2' panicked at tests/all_tests/t_u64x2.rs:70:3:
assertion `left == right` failed
  left: (18446744073709551608, 18446744073709551608)
 right: (184467440608246[497](https://github.com/Lokathor/wide/actions/runs/6215172943/job/16867793003#step:6:498)20, 18446744060824649720)

---- t_u64x2::impl_shr_for_u64x2 stdout ----
thread 't_u64x2::impl_shr_for_u64x2' panicked at tests/all_tests/t_u64x2.rs:79:3:
assertion `left == right` failed
  left: (4611686018427387903, 4611686018427387903)
 right: (4611686015206162431, 4611686015206162431)

---- t_u64x4::impl_shl_for_u64x4 stdout ----
thread 't_u64x4::impl_shl_for_u64x4' panicked at tests/all_tests/t_u64x4.rs:72:3:
assertion `left == right` failed
  left: (18446744073709551608, 18446744073709551608, 262140, 0)
 right: (18446744060824649720, 18446744060824649720, 262140, 0)

**Comment by mcroomp** [comment]
[#](https://github.com/rust-lang/rust/issues/116177)

**Comment by mcroomp** [comment]
this is fixed now in LLVM
